
package Vistas;

import java.awt.Cursor;
import javax.swing.JOptionPane;
public class Panel extends javax.swing.JFrame {

    /**
     * Creates new form Panel
     */
    public Panel() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setExtendedState(Panel.MAXIMIZED_BOTH);
        this.setTitle("Panel");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        mnSistema = new javax.swing.JMenu();
        mtCerrar = new javax.swing.JMenuItem();
        mtSalir = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mtNuevo = new javax.swing.JMenuItem();
        mtAdministrar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mnSistema.setText("Sistema");

        mtCerrar.setText("Cerrar sesion");
        mtCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mtCerrarActionPerformed(evt);
            }
        });
        mnSistema.add(mtCerrar);

        mtSalir.setText("Salir");
        mtSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mtSalirActionPerformed(evt);
            }
        });
        mnSistema.add(mtSalir);

        jMenuBar1.add(mnSistema);

        jMenu2.setText("Clientes");

        mtNuevo.setText("Nuevo");
        mtNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mtNuevoActionPerformed(evt);
            }
        });
        jMenu2.add(mtNuevo);

        mtAdministrar.setText("Administrar");
        mtAdministrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mtAdministrarActionPerformed(evt);
            }
        });
        jMenu2.add(mtAdministrar);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 598, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 474, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mtCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mtCerrarActionPerformed
        int c = JOptionPane.showConfirmDialog(
            null,
            "¿desea cerrar secion?",
            "Cerrar Secion",
            JOptionPane.YES_NO_OPTION);
        if(c == JOptionPane.NO_OPTION){
            
        }else{
            JOptionPane.showMessageDialog(null, "NOS VEMOS");
            Login l = new Login();
            l.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_mtCerrarActionPerformed

    private void mtSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mtSalirActionPerformed
        int n = JOptionPane.showConfirmDialog(
            null,
            "¿Desea cerrar la aplicacion?",
            "Salir",
            JOptionPane.YES_NO_OPTION);
        
        if(n == JOptionPane.NO_OPTION){
            
        }
        else{
            JOptionPane.showMessageDialog(null, "ADIOS");
            System.exit(0);
        }
    }//GEN-LAST:event_mtSalirActionPerformed

    private void mtNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mtNuevoActionPerformed
        ClientesAgregar a = new ClientesAgregar();
        a.setVisible(true);
    }//GEN-LAST:event_mtNuevoActionPerformed

    private void mtAdministrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mtAdministrarActionPerformed
        ClientesAdmin c = new ClientesAdmin();
        c.setVisible(true);
        
    }//GEN-LAST:event_mtAdministrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Panel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu mnSistema;
    private javax.swing.JMenuItem mtAdministrar;
    private javax.swing.JMenuItem mtCerrar;
    private javax.swing.JMenuItem mtNuevo;
    private javax.swing.JMenuItem mtSalir;
    // End of variables declaration//GEN-END:variables
}
